name: Run UI-licious Tests
run-name: Run UI-licious Tests
env: 
  TEST_FILES:
    - "Login to Github"
    - "Search for uilicious-cli"
on:
  # sync uilicious projects on push
  push:
    branches:
      - 'main'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      # - name: Install uilicious-cli
      #   run: npm install -g uilicious-cli
      # - name: Upload UI-licious Project
      #   run: uilicious-cli upload ${{ vars.UILICIOUS_PROJECT_ID }} ${{ vars.UILICIOUS_TEST_DIR }} --key ${{ secrets.UILICIOUS_ACCESS_KEY }}
      - name: echo files
        run: |
        echo ${{env.TEST_FILES}}
        for f in ${{env.TEST_FILES}}
        do
          echo "Running test file: $f"
        done