name: Sync UI-licious Tests
run-name: Sync UI-licious Tests
on: [push]
env:
  UILICIOUS_PROJECT_ID: "LPstoizdG1UrShapUVhuwY"
  TEST_DIR: "./tests"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Install uilicious-cli
        run: npm install -g uilicious-cli
      - name: Download UI-licious Project
        run: uilicious-cli download ${{ env.UILICIOUS_PROJECT_ID }} ${{ env.TEST_DIR }} --key ${{ secrets.UILICIOUS_ACCESS_KEY }}
      - name: Commit changed files to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Auto-commit] Sync UI-licious Tests"